# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7d0910ab252d97e9df2ee7cf4d2111c571d2f483d118ea8fa851dbabb265166db1ea450bdfc62a726ca2ec6d5a61120ed31c0e5902226baeaa429c66a51926

test:
  secret_key_base: a737c9aa3bfcd558c38624d1cc29b601638ee9aca69715e53dc93b5167be21f40578b5d46b36d600ce096bd0269457b2fb1a454aa95e192c4ba4abc01f928775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
